\c movies_dev;

INSERT INTO movies_genre(genre, title, thumbnail, year, synopsis, duration, favorite)VALUES
('Action', 'Creed', 'https://i.imgur.com/NQTuLtb.mp4', 2015, 'The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed.', 133, 1),
('Action', 'Furious 7', 'https://i.imgur.com/7ax74eb.mp4', 2015, 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.', 137, 3),
('Action', 'Guardians of the Galaxy', 'https://i.imgur.com/AylKL2G.mp4', 2014, 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.', 121, 4),
('Action', 'Suicide Squad', 'https://i.imgur.com/hwUzoyu.mp4', 2016, 'A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.', 123, 5),
('Anime', 'Gundam 00','https://i.imgur.com/BR9EUGh.mp4', 2007, 'In the distant future, mankind has used up all of its fossil fuels, forcing them to turn to Solar Power as an alternate energy source. As a result, this causes a rift to form between richer and poorer nations, eventually leading to war. In the midst of this conflict, a mysterious military group known as Celestial Being aims to use force to bring peace to the world, by using special humanoid weapons known as Gundams.', 100, 7),
('Anime', 'Dragon Ball Super','https://i.imgur.com/6u0PCQK.mp4', 2015, 'Six months after the defeat of Majin Buu, The mighty Saiyan Son Goku continues his quest on becoming stronger.',100, 0),
('Anime','Attack on Titan', 'https://i.imgur.com/LItJ5qS.mp4', 2013, 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.', 100, 3),
('Anime', 'Bleach4', 'https://i.imgur.com/W3fTtFS.mp4', 2004, 'High school student Ichigo Kurosaki, who has the ability to see ghosts, gains soul reaper powers from Rukia Kuchiki and sets out to save the world from ''Hollows''.', 100, 8),
('Award-Winning', 'Forest Gump', 'https://i.imgur.com/V6WMXYx.mp4', 1994, 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.', 142, 9),
('Award-Winning','The Matrix','https://i.imgur.com/QzJe4nJ.mp4', 1999, 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 136, 5),
('Award-Winning', 'Pulp Fiction', 'https://i.imgur.com/8xf630M.mp4' , 1994, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 154, 7),
('Award-Winning', 'Mia Madre', 'https://i.imgur.com/mRz7x3g.mp4', 2015, 'Margherita, a director in the middle of an existential crisis, has to deal with the inevitable and still unacceptable loss of her mother.', 106, 9),
('Children & Family', 'Finding Nemo', 'https://i.imgur.com/HtjzC5p.mp4', 2003, 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', 100, 10);